id: P009184
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:00.694270
source_metadata:
  id: bdr:W19995
  title: ཡིག་རིགས་འབྲི་སྟངས་ཀྱི་རྣམ་གཞག
  author: ''
  volumes:
    5d1daf61e52a47a0a5dbdb946b2750ab:
      image_group_id: I4729
      title: ''
      volume_number: 1
      total_pages: 197
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
