id: IADF8AD3B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:50:27+00:00'
last_modified: '2022-06-08T09:12:57.456699+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19995
  title: ཡིག་རིགས་འབྲི་སྟངས་ཀྱི་རྣམ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    FA49:
      image_group_id: I4729
      title: ''
      total_pages: 197
      order: 1
      base_file: FA49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
